name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Clean
        shell: bash
        run: make clean

      - name: Get dependencies
        shell: bash
        run: pod install

      - name: Build LibrePass.ipa
        shell: bash
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-iphoneos
          path: ./Build/Release-iphoneos/LibrePass.ipa
          
